<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	  <UserSecretsId>877b30ec-b167-41a7-886e-da1bce36a288</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Users\**" />
	  <EmbeddedResource Remove="Users\**" />
	  <None Remove="Users\**" />
	  <Page Remove="Users\**" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Images\" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Fonts\microsoftsansserif.ttf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\TsvikSPDemo.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Black.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-BlackItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Bold.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-BoldItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Heavy.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-HeavyItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Light.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-LightItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Regular.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-SemiBold.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-SemiBoldItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-Thin.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-UltraLight.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Fonts\Aileron-UltraLightItalic.otf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="SharpVectors" Version="1.8.4.2" />
	</ItemGroup>

</Project>